version: '3'

# ------------------------------------------------------------------------------
# These images must be built in advance, or docker-compose will build them.
# cd database/ol7_19
# docker build -t ol7_19:latest .
# 
# cd ords/ol7_ords
# docker build -t ol7_ords:latest .
#
# Run it.
# docker-compose up
# ------------------------------------------------------------------------------

services:
  # ORDS service
  ords:
    container_name: ${CONTAINER_NAME}_ords
    build:
      context: ./ol7_ords/
      dockerfile: Dockerfile
    depends_on:
      - db
    image: ol7_ords:latest
    volumes:
      - ./volumes/ol7_19_ords_tomcat:/u01/config/instance1
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_SERVICE=${DB_SERVICE}
      - APEX_PUBLIC_USER_PASSWORD=${APEX_PUBLIC_USER_PASSWORD}
      - APEX_TABLESPACE=${APEX_TABLESPACE}
      - TEMP_TABLESPACE=${TEMP_TABLESPACE}
      - APEX_LISTENER_PASSWORD=${APEX_LISTENER_PASSWORD}
      - APEX_REST_PASSWORD=${APEX_REST_PASSWORD}
      - PUBLIC_PASSWORD=${PUBLIC_PASSWORD}
      - SYS_PASSWORD=${SYS_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - BIND_ADDRESS=${BIND_ADDRESS}
      - APEX_HTTP_PORT=${APEX_HTTP_PORT}
      - APEX_HTTPS_PORT=${APEX_HTTPS_PORT}
      - PORTAINER_PORT=${PORTAINER_PORT}
      - CONTAINER_NAME=${CONTAINER_NAME}
    ports:
      - "${BIND_ADDRESS}:${APEX_HTTP_PORT}:8080"
      - "${BIND_ADDRESS}:${APEX_HTTPS_PORT}:8443"

    networks:
      - oracle_network
    restart: unless-stopped

  # Oracle Database service
  db:
    container_name: ${CONTAINER_NAME}_db
    build:
      context: ./ol7_19/
      dockerfile: Dockerfile
    image: ol7_19:latest
    # Use persistent volume of your choice.
    volumes:
      - ./volumes/ol7_19_ords_db:/u02
    environment:
      - SYS_PASSWORD=${SYS_PASSWORD}
      - PDB_PASSWORD=${PDB_PASSWORD}
      - APEX_EMAIL=${APEX_EMAIL}
      - APEX_PASSWORD=${APEX_PASSWORD}
    ports:
      - "1521:1521"
    networks:
      - oracle_network
    restart: unless-stopped

  # Portainer
  portainer:
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${BIND_ADDRESS}:${PORTAINER_PORT}:9000"
    restart: unless-stopped

volumes:
  portainer_data:

networks:
  oracle_network: